# Generated by Django 4.0.7 on 2026-05-16 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='slug',
            field=models.SlugField(blank=True, max_length=225, unique=True),
        ),
    ]
